In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('survey_data_messy.csv')

print("Shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())
print("\nFirst 5 rows:")
df.head()

Shape: (50, 11)

Column names:
['response_id', 'respondent_name', 'age', 'gender', 'department', 'employment_status', 'salary_range', 'satisfaction', 'recommend', 'feedback', 'survey_date']

First 5 rows:

,response_id,respondent_name,age,gender,department,employment_status,salary_range,satisfaction,recommend,feedback,survey_date
0,R001,John Smith,34,Male,Sales,Full-time,50000-75000,Very Satisfied,Yes,Great place to work!,2024-01-15
1,R002,sarah connor,28,female,Marketing,full-time,50000-75000,very satisfied,yes,Love the team culture,2024-01-15
2,R003,MIKE JOHNSON,45,MALE,sales,Full Time,75000-100000,Satisfied,Yes,Good benefits package,2024-01-16
3,R004,Emily Davis,31,Female,Human Resources,Part-time,25000-50000,Neutral,Maybe,It's okay I guess,2024-01-16
4,R005,Dr. Robert Brown,52,M,IT,Full-time,100000+,Very Satisfied,Yes,Excellent growth opportunities,2024-01-17

In [2]:
df.head(10)

,response_id,respondent_name,age,gender,department,employment_status,salary_range,satisfaction,recommend,feedback,survey_date
0,R001,John Smith,34,Male,Sales,Full-time,50000-75000,Very Satisfied,Yes,Great place to work!,2024-01-15
1,R002,sarah connor,28,female,Marketing,full-time,50000-75000,very satisfied,yes,Love the team culture,2024-01-15
2,R003,MIKE JOHNSON,45,MALE,sales,Full Time,75000-100000,Satisfied,Yes,Good benefits package,2024-01-16
3,R004,Emily Davis,31,Female,Human Resources,Part-time,25000-50000,Neutral,Maybe,It's okay I guess,2024-01-16
4,R005,Dr. Robert Brown,52,M,IT,Full-time,100000+,Very Satisfied,Yes,Excellent growth opportunities,2024-01-17
5,R006,jessica wilson,26,f,marketing,Fulltime,25000-50000,satisfied,yes,Nice office space,2024-01-17
6,R007,Mr. David Lee,38,Male,Sales,Contract,50000-75000,Dissatisfied,No,Poor management communication,2024-01-18
7,R008,Amanda Martinez,29,Female,HR,Full-time,50000-75000,Very Satisfied,YES,Amazing colleagues!,2024-01-18
8,R009,chris taylor,41,male,Information Technology,full time,75000-100000,Neutral,maybe,Could be better,2024-01-19
9,R010,Prof. Lisa Anderson,47,Female,R&D,Full-time,100000+,Satisfied,Yes,Great research facilities,2024-01-19

In [3]:
print(df['gender'].unique())

['Male' 'female' 'MALE' 'Female' 'M' 'f' 'male' ' Male' 'F' ' male'
 'FEMALE' 'm' '  Male']

In [4]:
# strip whitespace
df['gender'] = df['gender'].str.strip()

In [5]:
print(df['gender'].unique())

['Male' 'female' 'MALE' 'Female' 'M' 'f' 'male' 'F' 'FEMALE' 'm']

In [6]:
# mapping dictionary
gender_mapping = {
    'MALE': 'Male',
    'M': 'Male',
    'male': 'Male',
    'm': 'Male',
    
    'female': 'Female',
    'f': 'Female',
    'F': 'Female',
    'FEMALE': 'Female'
}

In [7]:
df['gender'] = df['gender'].replace(gender_mapping)
print(df['gender'].unique())

['Male' 'Female']

In [8]:
# employment status column 
print(df['employment_status'].unique())

['Full-time' 'full-time' 'Full Time' 'Part-time' 'Fulltime' 'Contract'
 'full time' 'Part time' 'Contractor' 'Intern' 'Freelance' 'intern']

In [9]:
# strip whitespace 
df['employment_status'] = df['employment_status'].str.strip()

In [10]:
df['employment_status'].unique()

array(['Full-time', 'full-time', 'Full Time', 'Part-time', 'Fulltime',
       'Contract', 'full time', 'Part time', 'Contractor', 'Intern',
       'Freelance', 'intern'], dtype=object)

In [11]:
# mapping dictionary
employ_status_mapping = {
    'full-time': 'Full-time',
    'Full Time': 'Full-time',
    'Fulltime': 'Full-time',
    'full time': 'Full-time',
    
    'Part time': 'Part-time',
    
    'Contractor': 'Contract',
    'Freelance': 'Contract',
    
    'intern': 'Intern'
}

In [12]:
df['employment_status'] = df['employment_status'].replace(employ_status_mapping)
print(df['employment_status'].unique())

['Full-time' 'Part-time' 'Contract' 'Intern']

In [13]:
# department column 
print(df['department'].unique())

['Sales' '  Marketing' 'sales' 'Human Resources' 'IT' 'marketing' 'HR'
 'Information Technology' 'R&D' 'Mktg' 'IT Department' 'Human Resource'
 'R and D' 'marketing department' 'Sales Team' 'Research & Development'
 'Mkt' 'sales department' 'Tech' 'Marketing' 'I.T.' 'Mrkting'
 'Research and Development' 'hr' 'information technology' 'HR Dept'
 'Research' 'mktg' 'R & D' 'Marketng']

In [14]:
# strip whitespace
df['department'] = df['department'].str.strip()

In [15]:
# mapping dictionary
department_mapping = {
    'sales': 'Sales',
    'Sales Team': 'Sales',
    'sales department': 'Sales',
    
    'marketing': 'Marketing',
    'Mktg': 'Marketing',
    'Mkt': 'Marketing',
    'mktg': 'Marketing',
    'Mrkting': 'Marketing',
    'Marketng': 'Marketing',
    'marketing department': 'Marketing',
    
    'I.T.': 'IT',
    'Tech': 'IT',
    'Information Technology': 'IT',
    'IT Department': 'IT',
    'information technology': 'IT',
    
    'HR': 'HR',
    'hr': 'HR',
    'Human Resources': 'HR',
    'Human Resource': 'HR',
    'HR Dept': 'HR',
    
    'R and D': 'R&D',
    'R & D': 'R&D',
    'Research & Development': 'R&D',
    'Research and Development': 'R&D',
    'Research': 'R&D'
}

In [16]:
df['department'] = df['department'].replace(department_mapping)
print(df['department'].unique())

['Sales' 'Marketing' 'HR' 'IT' 'R&D']

In [17]:
# satisfaction column
print(df['satisfaction'].unique())

['Very Satisfied' 'very satisfied' 'Satisfied' 'Neutral' 'satisfied'
 'Dissatisfied' 'Very Dissatisfied' 'SATISFIED']

In [18]:
df['satisfaction'] = df['satisfaction'].str.strip()

In [19]:
# mapping dictionary
satisfaction_mapping = {
    'very satisfied': 'Very Satisfied', 

    'satisfied': 'Satisfied', 
    'SATISFIED': 'Satisfied',
}

In [20]:
df['satisfaction'] = df['satisfaction'].replace(satisfaction_mapping)
print(df['satisfaction'].unique())

['Very Satisfied' 'Satisfied' 'Neutral' 'Dissatisfied' 'Very Dissatisfied']

In [21]:
# recommend column 
print(df['recommend'].unique())

['Yes' 'yes' 'Maybe' 'No' 'YES' 'maybe' 'Y' 'N' nan 'no']

In [22]:
print(df['recommend'].isna().sum())

1

In [23]:
# strip whitespace
df['recommend'] = df['recommend'].str.strip()

In [24]:
recommend_mapping = {
    'yes': 'Yes', 
    'YES': 'Yes', 
    'Y': 'Yes',

    'maybe': 'Maybe', 

    'N': 'No',
    'no': 'No', 
}

In [25]:
df['recommend'] = df['recommend'].replace(recommend_mapping)
print(df['recommend'].unique())

['Yes' 'Maybe' 'No' nan]

In [26]:
print(df['respondent_name'].head(20))

0              John Smith
1            sarah connor
2            MIKE JOHNSON
3             Emily Davis
4        Dr. Robert Brown
5          jessica wilson
6           Mr. David Lee
7         Amanda Martinez
8            chris taylor
9     Prof. Lisa Anderson
10            kevin white
11           Rachel Green
12          THOMAS HARRIS
13        Ms. Nancy Clark
14           daniel lewis
15          Olivia Walker
16             james hall
17           Sophia Young
18       Dr. William King
19             emma scott
Name: respondent_name, dtype: object

In [27]:
# cleaning 'respondent_name' column 
titles = ['Dr. ', 'Mr. ', 'Ms. ', 'Prof. ']
for title in titles:
    df['respondent_name'] = df['respondent_name'].str.replace(title, '', regex=False)

In [28]:
print(df['respondent_name'].head(20))

0          John Smith
1        sarah connor
2        MIKE JOHNSON
3         Emily Davis
4        Robert Brown
5      jessica wilson
6           David Lee
7     Amanda Martinez
8        chris taylor
9       Lisa Anderson
10        kevin white
11       Rachel Green
12      THOMAS HARRIS
13        Nancy Clark
14       daniel lewis
15      Olivia Walker
16         james hall
17       Sophia Young
18       William King
19         emma scott
Name: respondent_name, dtype: object

In [29]:
# fix capitalization
df['respondent_name'] = df['respondent_name'].str.title()
print(df['respondent_name'].head(20))

0          John Smith
1        Sarah Connor
2        Mike Johnson
3         Emily Davis
4        Robert Brown
5      Jessica Wilson
6           David Lee
7     Amanda Martinez
8        Chris Taylor
9       Lisa Anderson
10        Kevin White
11       Rachel Green
12      Thomas Harris
13        Nancy Clark
14       Daniel Lewis
15      Olivia Walker
16         James Hall
17       Sophia Young
18       William King
19         Emma Scott
Name: respondent_name, dtype: object

In [30]:
print(df['feedback'].head(20))

0               Great place to work!
1              Love the team culture
2              Good benefits package
3                It's okay I guess
4     Excellent growth opportunities
5                  Nice office space
6      Poor management communication
7                Amazing colleagues!
8                    Could be better
9          Great research facilities
10            Good work-life balance
11                               NaN
12                Outdated equipment
13             Supportive management
14                Average experience
15               Learning a lot here
16       Excellent training programs
17            Limited growth options
18              Top-notch facilities
19                  Great first job!
Name: feedback, dtype: object

In [31]:
print(df['feedback'].value_counts(dropna=False))

feedback
NaN                               2
Great place to work!              1
Love the team culture             1
  It's okay I guess               1
Good benefits package             1
Nice office space                 1
Poor management communication     1
Amazing colleagues!               1
Excellent growth opportunities    1
Could be better                   1
Great research facilities         1
Good work-life balance            1
Outdated equipment                1
Supportive management             1
Average experience                1
Learning a lot here               1
Excellent training programs       1
Limited growth options            1
Top-notch facilities              1
Great first job!                  1
No comment                        1
Good company culture              1
Too much bureaucracy              1
Love my team!                     1
Flexible hours                    1
Great mentorship                  1
Decent workplace                  1
Helpful HR team                   1
Innovative projects               1
Just okay                         1
Good tech stack                   1
Creative environment              1
Quality research work             1
Supportive team                   1
Commission structure unfair       1
Room for improvement              1
Good policies                     1
Exciting projects!                1
Competitive salary                1
Nice office location              1
Flexible but limited              1
Academic freedom                  1
Learning opportunity              1
High pressure environment         1
Creative freedom!                 1
Contract uncertainty              1
Fair treatment                    1
Cutting-edge work                 1
Amazing experience!               1
Name: count, dtype: int64

In [32]:
df['feedback'] = df['feedback'].str.strip()

In [33]:
import numpy as np
df['feedback'] = df['feedback'].replace('No comment', np.nan)

In [34]:
print(df['feedback'].isna().sum())

3

In [35]:
# verify 
print("verify columns are clean")
print(f"\nGender unique: {df['gender'].unique()}")
print(f"\nEmployment status unique: {df['employment_status'].unique()}")
print(f"\nDepartment unique: {df['department'].unique()}")
print(f"\nSatisfaction unique: {df['satisfaction'].unique()}")
print(f"\nRecommend unique: {df['recommend'].unique()}")
print(f"\nMissing values:\n{df.isna().sum()}")

verify columns are clean

Gender unique: ['Male' 'Female']

Employment status unique: ['Full-time' 'Part-time' 'Contract' 'Intern']

Department unique: ['Sales' 'Marketing' 'HR' 'IT' 'R&D']

Satisfaction unique: ['Very Satisfied' 'Satisfied' 'Neutral' 'Dissatisfied' 'Very Dissatisfied']

Recommend unique: ['Yes' 'Maybe' 'No' nan]

Missing values:
response_id          0
respondent_name      0
age                  0
gender               0
department           0
employment_status    0
salary_range         0
satisfaction         0
recommend            1
feedback             3
survey_date          0
dtype: int64

In [36]:
df.to_csv('survey_data_clean.csv', index=False)
print("Cleaned data saved!")

Cleaned data saved!